# Generated by Django 4.1 on 2024-08-28 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=128)),
                ('code', models.CharField(db_column='code', max_length=256, unique=True)),
                ('address', models.TextField(db_column='address', max_length=360)),
                ('latitude', models.FloatField(db_column='latitude')),
                ('longitude', models.FloatField(db_column='longitude')),
                ('status', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor')], db_column='status', max_length=64)),
                ('network_status', models.CharField(choices=[('ONLINE', 'On Line'), ('OFFLINE', 'Off Line'), ('WARNING', 'Warning')], db_column='network_status', max_length=64)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_pops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'POPs',
                'db_table': 'pops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POPDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=256, unique=True)),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('status', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor')], db_column='status', max_length=64)),
                ('remark', models.TextField(blank=True, db_column='remark', max_length=512, null=True)),
                ('phy_details', models.JSONField(blank=True, db_column='phy_details', null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('pop_name', models.ForeignKey(db_column='pop_name', on_delete=django.db.models.deletion.CASCADE, to='pop.pop')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pop Devices',
                'db_table': 'pop_devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POPDeviceState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_column='topic', max_length=256)),
                ('time_range', models.CharField(choices=[('TODAY', 'Today'), ('LAST_7_DAYS', 'Last 7 days'), ('LAST_30_DAYS', 'Last 30 days'), ('THIS_YEAR', 'This Year')], db_column='time_range', max_length=256)),
                ('data', models.JSONField(db_column='data')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('device_code', models.ForeignKey(db_column='device_code', on_delete=django.db.models.deletion.CASCADE, to='pop.popdevice')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pop Device States',
                'db_table': 'pop_device_states',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='popdevicestate',
            index=models.Index(fields=['created_at'], name='pop_device__created_92ffb3_idx'),
        ),
        migrations.AddIndex(
            model_name='popdevicestate',
            index=models.Index(fields=['is_active'], name='pop_device__is_acti_9882fa_idx'),
        ),
        migrations.AddIndex(
            model_name='popdevice',
            index=models.Index(fields=['code'], name='pop_devices_code_7fbb04_idx'),
        ),
        migrations.AddIndex(
            model_name='popdevice',
            index=models.Index(fields=['status'], name='pop_devices_status_a72247_idx'),
        ),
        migrations.AddIndex(
            model_name='popdevice',
            index=models.Index(fields=['is_active'], name='pop_devices_is_acti_f871b6_idx'),
        ),
        migrations.AddIndex(
            model_name='popdevice',
            index=models.Index(fields=['created_at'], name='pop_devices_created_41f063_idx'),
        ),
    ]
