# Generated by Django 4.1 on 2025-03-13 05:58

from django.db import migrations, models
import djongo.models.fields
import pop.ups_model


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0003_ccclenvironment_ccclgenerator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpsModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('data', djongo.models.fields.ArrayField(model_container=pop.ups_model.DataItem)),
            ],
            options={
                'db_table': 'ups_status',
            },
        ),
    ]
