# Generated by Django 4.1 on 2025-03-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0004_upsmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upsmodel',
            table=None,
        ),
    ]
