# Generated by Django 4.1 on 2025-03-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0005_alter_upsmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upsmodel',
            table='pop_upsdata',
        ),
    ]
