# Generated by Django 4.1 on 2025-03-13 09:32

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0006_alter_upsmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('oid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
