# Generated by Django 4.1 on 2025-03-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0007_dataitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
