# Generated by Django 4.1 on 2025-03-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0008_alter_dataitem_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataItem',
        ),
    ]
