# Generated by Django 4.1 on 2025-03-13 09:47

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0009_delete_dataitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsmodel',
            name='data',
            field=djongo.models.fields.JSONField(),
        ),
    ]
