# Generated by Django 4.1 on 2025-03-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0010_alter_upsmodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsmodel',
            name='timestamp',
            field=models.CharField(max_length=30),
        ),
    ]
