# Generated by Django 4.1 on 2025-03-23 17:06

from django.db import migrations, models
import djongo.models.fields
import pop.solar_model


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0011_alter_upsmodel_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarReading',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('current', djongo.models.fields.EmbeddedField(model_container=pop.solar_model.CurrentData)),
                ('power', djongo.models.fields.EmbeddedField(model_container=pop.solar_model.PowerData)),
                ('energy_consumption', djongo.models.fields.EmbeddedField(model_container=pop.solar_model.EnergyConsumption)),
            ],
            options={
                'db_table': 'pop_solar_readings',
            },
        ),
    ]
