# Generated by Django 4.1 on 2025-03-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0012_solarreading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryEnyNowDataModelCPM',
        ),
    ]
