# Generated by Django 4.1 on 2025-03-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0013_delete_temporaryenynowdatamodelcpm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryCCCLGenerator',
        ),
    ]
