# Generated by Django 4.1 on 2025-03-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0014_delete_temporaryccclgenerator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryRTModelCPM',
        ),
    ]
