--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE dcim_user;
ALTER ROLE dcim_user WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'md53bc7b1ac010bfbecd5346f541706f591';






--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Debian 12.22-1.pgdg120+1)
-- Dumped by pg_dump version 12.22 (Debian 12.22-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- Database "dcim" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Debian 12.22-1.pgdg120+1)
-- Dumped by pg_dump version 12.22 (Debian 12.22-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dcim; Type: DATABASE; Schema: -; Owner: dcim_user
--

CREATE DATABASE dcim WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';


ALTER DATABASE dcim OWNER TO dcim_user;

\connect dcim

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO dcim_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: dcim_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO dcim_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dcim_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO dcim_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: dcim_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO dcim_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: dcim_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO dcim_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: dcim_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO dcim_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: dcim_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO dcim_user;

--
-- Name: pop_device_states; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.pop_device_states (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    id uuid NOT NULL,
    topic character varying(256) NOT NULL,
    time_range character varying(256) NOT NULL,
    data jsonb NOT NULL,
    created_by uuid,
    device_code uuid NOT NULL,
    updated_by uuid
);


ALTER TABLE public.pop_device_states OWNER TO dcim_user;

--
-- Name: pop_devices; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.pop_devices (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    id uuid NOT NULL,
    code character varying(256) NOT NULL,
    name character varying(256) NOT NULL,
    status character varying(64) NOT NULL,
    remark text,
    phy_details jsonb,
    created_by uuid,
    pop_name uuid NOT NULL,
    updated_by uuid
);


ALTER TABLE public.pop_devices OWNER TO dcim_user;

--
-- Name: pops; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.pops (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    id uuid NOT NULL,
    name character varying(128) NOT NULL,
    code character varying(256) NOT NULL,
    address text NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    status character varying(64) NOT NULL,
    network_status character varying(64) NOT NULL,
    created_by uuid,
    updated_by uuid,
    user_id uuid NOT NULL
);


ALTER TABLE public.pops OWNER TO dcim_user;

--
-- Name: role; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.role (
    role_id uuid NOT NULL,
    name character varying(64) NOT NULL,
    key character varying(64) NOT NULL
);


ALTER TABLE public.role OWNER TO dcim_user;

--
-- Name: user; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public."user" (
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    user_id uuid NOT NULL,
    full_name character varying(128) NOT NULL,
    email character varying(128) NOT NULL,
    password character varying(256) NOT NULL,
    contact_number character varying(15) NOT NULL,
    role_id uuid
);


ALTER TABLE public."user" OWNER TO dcim_user;

--
-- Name: user_groups; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.user_groups (
    id bigint NOT NULL,
    customuser_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_groups OWNER TO dcim_user;

--
-- Name: user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: dcim_user
--

ALTER TABLE public.user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_user_permissions; Type: TABLE; Schema: public; Owner: dcim_user
--

CREATE TABLE public.user_user_permissions (
    id bigint NOT NULL,
    customuser_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_user_permissions OWNER TO dcim_user;

--
-- Name: user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: dcim_user
--

ALTER TABLE public.user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add role	6	add_role
22	Can change role	6	change_role
23	Can delete role	6	delete_role
24	Can view role	6	view_role
25	Can add custom user	7	add_customuser
26	Can change custom user	7	change_customuser
27	Can delete custom user	7	delete_customuser
28	Can view custom user	7	view_customuser
29	Can add pop	8	add_pop
30	Can change pop	8	change_pop
31	Can delete pop	8	delete_pop
32	Can view pop	8	view_pop
33	Can add pop device	9	add_popdevice
34	Can change pop device	9	change_popdevice
35	Can delete pop device	9	delete_popdevice
36	Can view pop device	9	view_popdevice
37	Can add pop device state	10	add_popdevicestate
38	Can change pop device state	10	change_popdevicestate
39	Can delete pop device state	10	delete_popdevicestate
40	Can view pop device state	10	view_popdevicestate
41	Can add eny now data model cpm	11	add_enynowdatamodelcpm
42	Can change eny now data model cpm	11	change_enynowdatamodelcpm
43	Can delete eny now data model cpm	11	delete_enynowdatamodelcpm
44	Can view eny now data model cpm	11	view_enynowdatamodelcpm
45	Can add last30 days eny now data model cpm	12	add_last30daysenynowdatamodelcpm
46	Can change last30 days eny now data model cpm	12	change_last30daysenynowdatamodelcpm
47	Can delete last30 days eny now data model cpm	12	delete_last30daysenynowdatamodelcpm
48	Can view last30 days eny now data model cpm	12	view_last30daysenynowdatamodelcpm
49	Can add last30 days rt model cpm	13	add_last30daysrtmodelcpm
50	Can change last30 days rt model cpm	13	change_last30daysrtmodelcpm
51	Can delete last30 days rt model cpm	13	delete_last30daysrtmodelcpm
52	Can view last30 days rt model cpm	13	view_last30daysrtmodelcpm
53	Can add last30 days thermo hygrometer mongo model	14	add_last30daysthermohygrometermongomodel
54	Can change last30 days thermo hygrometer mongo model	14	change_last30daysthermohygrometermongomodel
55	Can delete last30 days thermo hygrometer mongo model	14	delete_last30daysthermohygrometermongomodel
56	Can view last30 days thermo hygrometer mongo model	14	view_last30daysthermohygrometermongomodel
57	Can add last7 days eny now data model cpm	15	add_last7daysenynowdatamodelcpm
58	Can change last7 days eny now data model cpm	15	change_last7daysenynowdatamodelcpm
59	Can delete last7 days eny now data model cpm	15	delete_last7daysenynowdatamodelcpm
60	Can view last7 days eny now data model cpm	15	view_last7daysenynowdatamodelcpm
61	Can add last7 days rt model cpm	16	add_last7daysrtmodelcpm
62	Can change last7 days rt model cpm	16	change_last7daysrtmodelcpm
63	Can delete last7 days rt model cpm	16	delete_last7daysrtmodelcpm
64	Can view last7 days rt model cpm	16	view_last7daysrtmodelcpm
65	Can add last7 days thermo hygrometer mongo model	17	add_last7daysthermohygrometermongomodel
66	Can change last7 days thermo hygrometer mongo model	17	change_last7daysthermohygrometermongomodel
67	Can delete last7 days thermo hygrometer mongo model	17	delete_last7daysthermohygrometermongomodel
68	Can view last7 days thermo hygrometer mongo model	17	view_last7daysthermohygrometermongomodel
69	Can add rt model cpm	18	add_rtmodelcpm
70	Can change rt model cpm	18	change_rtmodelcpm
71	Can delete rt model cpm	18	delete_rtmodelcpm
72	Can view rt model cpm	18	view_rtmodelcpm
73	Can add temporary eny now data model cpm	19	add_temporaryenynowdatamodelcpm
74	Can change temporary eny now data model cpm	19	change_temporaryenynowdatamodelcpm
75	Can delete temporary eny now data model cpm	19	delete_temporaryenynowdatamodelcpm
76	Can view temporary eny now data model cpm	19	view_temporaryenynowdatamodelcpm
77	Can add temporary rt model cpm	20	add_temporaryrtmodelcpm
78	Can change temporary rt model cpm	20	change_temporaryrtmodelcpm
79	Can delete temporary rt model cpm	20	delete_temporaryrtmodelcpm
80	Can view temporary rt model cpm	20	view_temporaryrtmodelcpm
81	Can add temp thermo hygrometer mongo model	21	add_tempthermohygrometermongomodel
82	Can change temp thermo hygrometer mongo model	21	change_tempthermohygrometermongomodel
83	Can delete temp thermo hygrometer mongo model	21	delete_tempthermohygrometermongomodel
84	Can view temp thermo hygrometer mongo model	21	view_tempthermohygrometermongomodel
85	Can add thermo hygrometer mongo model	22	add_thermohygrometermongomodel
86	Can change thermo hygrometer mongo model	22	change_thermohygrometermongomodel
87	Can delete thermo hygrometer mongo model	22	delete_thermohygrometermongomodel
88	Can view thermo hygrometer mongo model	22	view_thermohygrometermongomodel
89	Can add this year eny now data model cpm	23	add_thisyearenynowdatamodelcpm
90	Can change this year eny now data model cpm	23	change_thisyearenynowdatamodelcpm
91	Can delete this year eny now data model cpm	23	delete_thisyearenynowdatamodelcpm
92	Can view this year eny now data model cpm	23	view_thisyearenynowdatamodelcpm
93	Can add this year rt model cpm	24	add_thisyearrtmodelcpm
94	Can change this year rt model cpm	24	change_thisyearrtmodelcpm
95	Can delete this year rt model cpm	24	delete_thisyearrtmodelcpm
96	Can view this year rt model cpm	24	view_thisyearrtmodelcpm
97	Can add this year thermo hygrometer mongo model	25	add_thisyearthermohygrometermongomodel
98	Can change this year thermo hygrometer mongo model	25	change_thisyearthermohygrometermongomodel
99	Can delete this year thermo hygrometer mongo model	25	delete_thisyearthermohygrometermongomodel
100	Can view this year thermo hygrometer mongo model	25	view_thisyearthermohygrometermongomodel
101	Can add today eny now data model cpm	26	add_todayenynowdatamodelcpm
102	Can change today eny now data model cpm	26	change_todayenynowdatamodelcpm
103	Can delete today eny now data model cpm	26	delete_todayenynowdatamodelcpm
104	Can view today eny now data model cpm	26	view_todayenynowdatamodelcpm
105	Can add today rt model cpm	27	add_todayrtmodelcpm
106	Can change today rt model cpm	27	change_todayrtmodelcpm
107	Can delete today rt model cpm	27	delete_todayrtmodelcpm
108	Can view today rt model cpm	27	view_todayrtmodelcpm
109	Can add today thermo hygrometer mongo model	28	add_todaythermohygrometermongomodel
110	Can change today thermo hygrometer mongo model	28	change_todaythermohygrometermongomodel
111	Can delete today thermo hygrometer mongo model	28	delete_todaythermohygrometermongomodel
112	Can view today thermo hygrometer mongo model	28	view_todaythermohygrometermongomodel
113	Can add cccl environment	29	add_ccclenvironment
114	Can change cccl environment	29	change_ccclenvironment
115	Can delete cccl environment	29	delete_ccclenvironment
116	Can view cccl environment	29	view_ccclenvironment
117	Can add cccl generator	30	add_ccclgenerator
118	Can change cccl generator	30	change_ccclgenerator
119	Can delete cccl generator	30	delete_ccclgenerator
120	Can view cccl generator	30	view_ccclgenerator
121	Can add last30 days cccl environment	31	add_last30daysccclenvironment
122	Can change last30 days cccl environment	31	change_last30daysccclenvironment
123	Can delete last30 days cccl environment	31	delete_last30daysccclenvironment
124	Can view last30 days cccl environment	31	view_last30daysccclenvironment
125	Can add last30 days cccl generator	32	add_last30daysccclgenerator
126	Can change last30 days cccl generator	32	change_last30daysccclgenerator
127	Can delete last30 days cccl generator	32	delete_last30daysccclgenerator
128	Can view last30 days cccl generator	32	view_last30daysccclgenerator
129	Can add last7 days cccl environment	33	add_last7daysccclenvironment
130	Can change last7 days cccl environment	33	change_last7daysccclenvironment
131	Can delete last7 days cccl environment	33	delete_last7daysccclenvironment
132	Can view last7 days cccl environment	33	view_last7daysccclenvironment
133	Can add last7 days cccl generator	34	add_last7daysccclgenerator
134	Can change last7 days cccl generator	34	change_last7daysccclgenerator
135	Can delete last7 days cccl generator	34	delete_last7daysccclgenerator
136	Can view last7 days cccl generator	34	view_last7daysccclgenerator
137	Can add temporary cccl environment	35	add_temporaryccclenvironment
138	Can change temporary cccl environment	35	change_temporaryccclenvironment
139	Can delete temporary cccl environment	35	delete_temporaryccclenvironment
140	Can view temporary cccl environment	35	view_temporaryccclenvironment
141	Can add temporary cccl generator	36	add_temporaryccclgenerator
142	Can change temporary cccl generator	36	change_temporaryccclgenerator
143	Can delete temporary cccl generator	36	delete_temporaryccclgenerator
144	Can view temporary cccl generator	36	view_temporaryccclgenerator
145	Can add this year cccl environment	37	add_thisyearccclenvironment
146	Can change this year cccl environment	37	change_thisyearccclenvironment
147	Can delete this year cccl environment	37	delete_thisyearccclenvironment
148	Can view this year cccl environment	37	view_thisyearccclenvironment
149	Can add this year cccl generator	38	add_thisyearccclgenerator
150	Can change this year cccl generator	38	change_thisyearccclgenerator
151	Can delete this year cccl generator	38	delete_thisyearccclgenerator
152	Can view this year cccl generator	38	view_thisyearccclgenerator
153	Can add today cccl environment	39	add_todayccclenvironment
154	Can change today cccl environment	39	change_todayccclenvironment
155	Can delete today cccl environment	39	delete_todayccclenvironment
156	Can view today cccl environment	39	view_todayccclenvironment
157	Can add today cccl generator	40	add_todayccclgenerator
158	Can change today cccl generator	40	change_todayccclgenerator
159	Can delete today cccl generator	40	delete_todayccclgenerator
160	Can view today cccl generator	40	view_todayccclgenerator
161	Can add ups model	41	add_upsmodel
162	Can change ups model	41	change_upsmodel
163	Can delete ups model	41	delete_upsmodel
164	Can view ups model	41	view_upsmodel
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-03-16 18:12:04.955392+00	e1f69be8-7cb7-44ec-9978-39f0288e62b5	admin	1	[{"added": {}}]	6	5be07222-ca5f-48e2-8f43-c0c73e5c668d
2	2025-03-16 18:12:26.619249+00	e1f69be8-7cb7-44ec-9978-39f0288e62b5	admin	2	[{"changed": {"fields": ["Name"]}}]	6	5be07222-ca5f-48e2-8f43-c0c73e5c668d
3	2025-03-16 18:12:34.217359+00	e1f69be8-7cb7-44ec-9978-39f0288e62b5	admin	2	[]	6	5be07222-ca5f-48e2-8f43-c0c73e5c668d
4	2025-03-16 18:12:40.860282+00	7bf2251d-8134-4469-9476-c3876ee87cd8	user	1	[{"added": {}}]	6	5be07222-ca5f-48e2-8f43-c0c73e5c668d
5	2025-03-16 18:16:04.646559+00	bc1efb6f-3900-4035-8ae8-2df1b84e59fe	admin@gmail.com	1	[{"added": {}}]	7	5be07222-ca5f-48e2-8f43-c0c73e5c668d
6	2025-03-16 18:16:09.030957+00	bc1efb6f-3900-4035-8ae8-2df1b84e59fe	admin@gmail.com	2	[{"changed": {"fields": ["Superuser status"]}}]	7	5be07222-ca5f-48e2-8f43-c0c73e5c668d
7	2025-03-16 18:17:25.118269+00	bc1efb6f-3900-4035-8ae8-2df1b84e59fe	admin@gmail.com	3		7	5be07222-ca5f-48e2-8f43-c0c73e5c668d
8	2025-03-16 18:21:21.811913+00	61526a69-c86f-4396-a8e4-5a8868b3a75b	admin@gmail.com	1	[{"added": {}}]	7	5be07222-ca5f-48e2-8f43-c0c73e5c668d
9	2025-03-16 18:21:26.260203+00	61526a69-c86f-4396-a8e4-5a8868b3a75b	admin@gmail.com	2	[{"changed": {"fields": ["Superuser status"]}}]	7	5be07222-ca5f-48e2-8f43-c0c73e5c668d
10	2025-03-16 18:21:56.514448+00	6aa50456-a3dd-46b4-86f7-d0be50082c2a	testuser@gmail.com	1	[{"added": {}}]	7	5be07222-ca5f-48e2-8f43-c0c73e5c668d
11	2025-03-16 18:22:13.38761+00	6aa50456-a3dd-46b4-86f7-d0be50082c2a	testuser@gmail.com	2	[{"changed": {"fields": ["Staff status", "Superuser status"]}}]	7	5be07222-ca5f-48e2-8f43-c0c73e5c668d
12	2025-03-16 18:23:40.728983+00	b8b9df59-d288-4eb3-be2d-314fe7f3d9f4	Colo City	1	[{"added": {}}]	8	5be07222-ca5f-48e2-8f43-c0c73e5c668d
13	2025-03-16 18:24:34.166981+00	e0ac95b7-834b-4c3c-97bf-2aeb8cdc4ef2	Green Power	1	[{"added": {}}]	8	5be07222-ca5f-48e2-8f43-c0c73e5c668d
14	2025-03-16 18:25:31.857588+00	5fad9405-6ec4-4e82-aef8-5d351c75c380	3071523B00003	1	[{"added": {}}]	9	5be07222-ca5f-48e2-8f43-c0c73e5c668d
15	2025-03-16 18:26:17.867367+00	92b6a2ae-5c9d-46c7-97b6-b47ce9f505e4	COLOCITY_THERMOHYGROMETER	1	[{"added": {}}]	9	5be07222-ca5f-48e2-8f43-c0c73e5c668d
16	2025-03-16 18:27:08.597676+00	b74446b3-e25a-465d-beeb-8c991c589b74	GREEN_POWER_GENERATOR	1	[{"added": {}}]	9	5be07222-ca5f-48e2-8f43-c0c73e5c668d
17	2025-03-16 18:27:30.893783+00	28169ac6-1978-48fb-bc76-52db2b8ea4f6	GREEN_POWER_THERMOHYGROMETER	1	[{"added": {}}]	9	5be07222-ca5f-48e2-8f43-c0c73e5c668d
18	2025-03-16 18:28:17.54628+00	f7fd4c15-d393-447e-a32e-13ef58160734	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
19	2025-03-16 18:28:34.129424+00	5cbf7060-b9e5-4a04-9a94-6f9a9739675f	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
20	2025-03-16 18:28:46.482926+00	915a38a7-1164-455b-b8f5-2b50c2e54f12	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
21	2025-03-16 18:29:03.267049+00	ac36b026-13a1-4031-b023-bbe2575a1e9d	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
22	2025-03-16 18:29:34.38842+00	a0570796-c199-43ca-9cbf-7b1a17d1ea13	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
23	2025-03-16 18:29:45.772758+00	64e2bee6-f59c-4acc-b1f4-b0dfef70d8bc	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
24	2025-03-16 18:29:57.648624+00	78e4ceb7-2e42-435f-94e0-b0447eb80dca	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
25	2025-03-16 18:30:10.911256+00	af7a35ba-4cf1-44d4-a76a-89f6c89d3e1c	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
26	2025-03-16 18:30:42.401866+00	37123f81-0a98-4e90-a5db-6c67406b589f	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
27	2025-03-16 18:30:56.702199+00	cad3237d-0531-461b-9127-c785973d972a	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
28	2025-03-16 18:31:09.703374+00	d4cc7513-faea-4352-ba8c-e35d6cb16f99	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
29	2025-03-16 18:31:24.135348+00	110545e3-30a8-45db-a0f9-82687bcad7f5	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
30	2025-03-16 18:32:14.430387+00	824ea9ec-ffd7-420e-8126-908bbdd3459c	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
31	2025-03-16 18:32:41.598563+00	2125f9da-6a46-41b0-8283-cc61413be19a	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
32	2025-03-16 18:32:58.055432+00	aa02ca7d-5b90-4fc4-b1ee-2b8480648249	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
33	2025-03-16 18:33:34.527948+00	b085f0fb-4ad9-4e94-83ce-08929878d003	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
34	2025-03-16 18:33:48.22074+00	2540a06a-472e-4686-b28e-353ea0cdbf34	3071523B00003	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
35	2025-03-16 18:34:09.68217+00	b085f0fb-4ad9-4e94-83ce-08929878d003	3071523B00003	3		10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
36	2025-03-16 18:35:32.595362+00	f590e668-1164-484e-9f03-67e2b2a8ed26	COLOCITY_THERMOHYGROMETER	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
37	2025-03-16 18:35:48.427184+00	619c5b59-4d64-44e1-b107-fb8e1c483aab	COLOCITY_THERMOHYGROMETER	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
38	2025-03-16 18:36:02.527347+00	43fb4b5d-c603-4cb4-9e51-9f8499ac7cef	COLOCITY_THERMOHYGROMETER	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
39	2025-03-16 18:36:20.210519+00	faeb1549-e3fd-4a88-94c4-ba88345cb344	COLOCITY_THERMOHYGROMETER	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
40	2025-03-16 18:36:46.968616+00	00c8caaf-9bef-45f2-8f7d-c3cff021c645	GREEN_POWER_GENERATOR	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
41	2025-03-16 18:37:09.594192+00	aee5d6c2-56de-4318-aeee-cb0b852f0a15	GREEN_POWER_GENERATOR	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
42	2025-03-16 18:37:26.032774+00	fdd3f69f-4313-41d7-86c1-4af70e7a0bb8	GREEN_POWER_GENERATOR	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
43	2025-03-16 18:37:46.830773+00	021372bf-82d6-48a9-a1fb-80f3568a7fa5	GREEN_POWER_GENERATOR	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
44	2025-03-16 18:38:08.00164+00	ab7783ca-b5d8-429b-a9ab-0594f0ade449	GREEN_POWER_THERMOHYGROMETER	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
45	2025-03-16 18:38:35.867704+00	58ab8532-db37-4e88-8b25-5ba4b27359f4	GREEN_POWER_THERMOHYGROMETER	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
46	2025-03-16 18:38:55.370237+00	ea4c16bd-adc8-485d-b10c-9636b07791fb	GREEN_POWER_THERMOHYGROMETER	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
47	2025-03-16 18:39:17.069499+00	63d79dc4-797a-4a45-96c6-7bd855222997	GREEN_POWER_THERMOHYGROMETER	1	[{"added": {}}]	10	5be07222-ca5f-48e2-8f43-c0c73e5c668d
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	account	role
7	account	customuser
8	pop	pop
9	pop	popdevice
10	pop	popdevicestate
11	pop	enynowdatamodelcpm
12	pop	last30daysenynowdatamodelcpm
13	pop	last30daysrtmodelcpm
14	pop	last30daysthermohygrometermongomodel
15	pop	last7daysenynowdatamodelcpm
16	pop	last7daysrtmodelcpm
17	pop	last7daysthermohygrometermongomodel
18	pop	rtmodelcpm
19	pop	temporaryenynowdatamodelcpm
20	pop	temporaryrtmodelcpm
21	pop	tempthermohygrometermongomodel
22	pop	thermohygrometermongomodel
23	pop	thisyearenynowdatamodelcpm
24	pop	thisyearrtmodelcpm
25	pop	thisyearthermohygrometermongomodel
26	pop	todayenynowdatamodelcpm
27	pop	todayrtmodelcpm
28	pop	todaythermohygrometermongomodel
29	pop	ccclenvironment
30	pop	ccclgenerator
31	pop	last30daysccclenvironment
32	pop	last30daysccclgenerator
33	pop	last7daysccclenvironment
34	pop	last7daysccclgenerator
35	pop	temporaryccclenvironment
36	pop	temporaryccclgenerator
37	pop	thisyearccclenvironment
38	pop	thisyearccclgenerator
39	pop	todayccclenvironment
40	pop	todayccclgenerator
41	pop	upsmodel
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-03-16 18:07:20.916827+00
2	contenttypes	0002_remove_content_type_name	2025-03-16 18:07:20.924742+00
3	auth	0001_initial	2025-03-16 18:07:20.959575+00
4	auth	0002_alter_permission_name_max_length	2025-03-16 18:07:20.964573+00
5	auth	0003_alter_user_email_max_length	2025-03-16 18:07:20.970792+00
6	auth	0004_alter_user_username_opts	2025-03-16 18:07:20.97886+00
7	auth	0005_alter_user_last_login_null	2025-03-16 18:07:20.984121+00
8	auth	0006_require_contenttypes_0002	2025-03-16 18:07:20.986365+00
9	auth	0007_alter_validators_add_error_messages	2025-03-16 18:07:20.993596+00
10	auth	0008_alter_user_username_max_length	2025-03-16 18:07:21.001523+00
11	auth	0009_alter_user_last_name_max_length	2025-03-16 18:07:21.009208+00
12	auth	0010_alter_group_name_max_length	2025-03-16 18:07:21.015535+00
13	auth	0011_update_proxy_permissions	2025-03-16 18:07:21.022491+00
14	auth	0012_alter_user_first_name_max_length	2025-03-16 18:07:21.028834+00
15	account	0001_initial	2025-03-16 18:07:21.072245+00
16	admin	0001_initial	2025-03-16 18:07:21.100401+00
17	admin	0002_logentry_remove_auto_add	2025-03-16 18:07:21.113466+00
18	admin	0003_logentry_add_action_flag_choices	2025-03-16 18:07:21.127434+00
19	pop	0001_initial	2025-03-16 18:07:21.295348+00
20	pop	0002_enynowdatamodelcpm_last30daysenynowdatamodelcpm_and_more	2025-03-16 18:07:21.319417+00
21	pop	0003_ccclenvironment_ccclgenerator_and_more	2025-03-16 18:07:21.342627+00
22	pop	0004_upsmodel	2025-03-16 18:07:21.346605+00
23	pop	0005_alter_upsmodel_table	2025-03-16 18:07:21.351629+00
24	pop	0006_alter_upsmodel_table	2025-03-16 18:07:21.359589+00
25	pop	0007_dataitem	2025-03-16 18:07:21.36619+00
26	pop	0008_alter_dataitem_value	2025-03-16 18:07:21.379686+00
27	pop	0009_delete_dataitem	2025-03-16 18:07:21.384869+00
28	pop	0010_alter_upsmodel_data	2025-03-16 18:07:21.391362+00
29	sessions	0001_initial	2025-03-16 18:07:21.404403+00
30	pop	0011_alter_upsmodel_timestamp	2025-03-16 20:13:00.398568+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
nsnlxki18wko150dfkyy4ubq8gbd5bns	.eJxVjLkOwjAMQP8lM4kS5xQjO99QObZDOdRKPSbEv9NKHWB-x1t1uC59t84ydXdWZxWr2AwAmjA2HYqALi14TZayl0gpFVan36wiPWXYW37gcBsNjcMy3avZFXPQ2VxHltflcP8GPc79ViMXGzBaxxWadSHmkBILJgyeEpPP1rmMMdbWCDZEYCU0tsjiM4P6fAH07EGH:1ttsSK:bZGV_JYXTB4bD6rnmVMRxE9GyWNxA39aYuH8Ieltau0	2025-03-30 18:11:24.534981+00
\.


--
-- Data for Name: pop_device_states; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.pop_device_states (created_at, updated_at, is_active, id, topic, time_range, data, created_by, device_code, updated_by) FROM stdin;
2025-03-16 18:28:17.542822+00	2025-03-16 18:28:17.542847+00	t	f7fd4c15-d393-447e-a32e-13ef58160734	MQTT_RT_DATA	TODAY	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:28:34.127758+00	2025-03-16 18:28:34.127782+00	t	5cbf7060-b9e5-4a04-9a94-6f9a9739675f	MQTT_RT_DATA	LAST_7_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:28:46.481962+00	2025-03-16 18:28:46.481986+00	t	915a38a7-1164-455b-b8f5-2b50c2e54f12	MQTT_RT_DATA	LAST_30_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:29:03.26631+00	2025-03-16 18:29:03.266324+00	t	ac36b026-13a1-4031-b023-bbe2575a1e9d	MQTT_RT_DATA	THIS_YEAR	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:29:34.387389+00	2025-03-16 18:29:34.387409+00	t	a0570796-c199-43ca-9cbf-7b1a17d1ea13	MQTT_ENY_NOW	TODAY	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:29:45.771658+00	2025-03-16 18:29:45.771687+00	t	64e2bee6-f59c-4acc-b1f4-b0dfef70d8bc	MQTT_ENY_NOW	LAST_7_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:29:57.647839+00	2025-03-16 18:29:57.647854+00	t	78e4ceb7-2e42-435f-94e0-b0447eb80dca	MQTT_ENY_NOW	LAST_30_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:30:10.910196+00	2025-03-16 18:30:10.910212+00	t	af7a35ba-4cf1-44d4-a76a-89f6c89d3e1c	MQTT_ENY_NOW	THIS_YEAR	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:30:42.400739+00	2025-03-16 18:30:42.400763+00	t	37123f81-0a98-4e90-a5db-6c67406b589f	MQTT_ENY_FRZ	TODAY	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:30:56.7014+00	2025-03-16 18:30:56.701415+00	t	cad3237d-0531-461b-9127-c785973d972a	MQTT_ENY_FRZ	LAST_7_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:31:09.702084+00	2025-03-16 18:31:09.702107+00	t	d4cc7513-faea-4352-ba8c-e35d6cb16f99	MQTT_ENY_FRZ	LAST_30_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:31:24.134585+00	2025-03-16 18:31:24.134601+00	t	110545e3-30a8-45db-a0f9-82687bcad7f5	MQTT_ENY_FRZ	THIS_YEAR	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:32:14.429362+00	2025-03-16 18:32:14.429393+00	t	824ea9ec-ffd7-420e-8126-908bbdd3459c	MQTT_DAY_DATA	TODAY	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:32:41.597807+00	2025-03-16 18:32:41.597822+00	t	2125f9da-6a46-41b0-8283-cc61413be19a	MQTT_DAY_DATA	LAST_7_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:32:58.054606+00	2025-03-16 18:32:58.054623+00	t	aa02ca7d-5b90-4fc4-b1ee-2b8480648249	MQTT_DAY_DATA	LAST_30_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:33:48.220018+00	2025-03-16 18:33:48.220033+00	t	2540a06a-472e-4686-b28e-353ea0cdbf34	MQTT_DAY_DATA	THIS_YEAR	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	5fad9405-6ec4-4e82-aef8-5d351c75c380	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:35:32.594462+00	2025-03-16 18:35:32.594479+00	t	f590e668-1164-484e-9f03-67e2b2a8ed26	DCIM/COLOCITY/ENV_01	TODAY	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	92b6a2ae-5c9d-46c7-97b6-b47ce9f505e4	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:35:48.425984+00	2025-03-16 18:35:48.426005+00	t	619c5b59-4d64-44e1-b107-fb8e1c483aab	DCIM/COLOCITY/ENV_01	LAST_7_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	92b6a2ae-5c9d-46c7-97b6-b47ce9f505e4	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:36:02.526498+00	2025-03-16 18:36:02.52652+00	t	43fb4b5d-c603-4cb4-9e51-9f8499ac7cef	DCIM/COLOCITY/ENV_01	LAST_30_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	92b6a2ae-5c9d-46c7-97b6-b47ce9f505e4	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:36:20.20912+00	2025-03-16 18:36:20.209142+00	t	faeb1549-e3fd-4a88-94c4-ba88345cb344	DCIM/COLOCITY/ENV_01	THIS_YEAR	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	92b6a2ae-5c9d-46c7-97b6-b47ce9f505e4	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:36:46.967817+00	2025-03-16 18:36:46.96784+00	t	00c8caaf-9bef-45f2-8f7d-c3cff021c645	CCCL/PURBACHAL/ENM_01	TODAY	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	b74446b3-e25a-465d-beeb-8c991c589b74	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:37:09.59331+00	2025-03-16 18:37:09.593333+00	t	aee5d6c2-56de-4318-aeee-cb0b852f0a15	CCCL/PURBACHAL/ENM_01	LAST_7_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	b74446b3-e25a-465d-beeb-8c991c589b74	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:37:26.031456+00	2025-03-16 18:37:26.031479+00	t	fdd3f69f-4313-41d7-86c1-4af70e7a0bb8	CCCL/PURBACHAL/ENM_01	LAST_30_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	b74446b3-e25a-465d-beeb-8c991c589b74	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:37:46.829856+00	2025-03-16 18:37:46.829871+00	t	021372bf-82d6-48a9-a1fb-80f3568a7fa5	CCCL/PURBACHAL/ENM_01	THIS_YEAR	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	b74446b3-e25a-465d-beeb-8c991c589b74	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:38:08.000837+00	2025-03-16 18:38:08.000853+00	t	ab7783ca-b5d8-429b-a9ab-0594f0ade449	CCCL/PURBACHAL/ENV_01	TODAY	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	28169ac6-1978-48fb-bc76-52db2b8ea4f6	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:38:35.866459+00	2025-03-16 18:38:35.866481+00	t	58ab8532-db37-4e88-8b25-5ba4b27359f4	CCCL/PURBACHAL/ENV_01	LAST_7_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	28169ac6-1978-48fb-bc76-52db2b8ea4f6	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:38:55.369262+00	2025-03-16 18:38:55.369277+00	t	ea4c16bd-adc8-485d-b10c-9636b07791fb	CCCL/PURBACHAL/ENV_01	LAST_30_DAYS	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	28169ac6-1978-48fb-bc76-52db2b8ea4f6	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:39:17.068259+00	2025-03-16 18:39:17.068286+00	t	63d79dc4-797a-4a45-96c6-7bd855222997	CCCL/PURBACHAL/ENV_01	THIS_YEAR	{"": ""}	61526a69-c86f-4396-a8e4-5a8868b3a75b	28169ac6-1978-48fb-bc76-52db2b8ea4f6	61526a69-c86f-4396-a8e4-5a8868b3a75b
\.


--
-- Data for Name: pop_devices; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.pop_devices (created_at, updated_at, is_active, id, code, name, status, remark, phy_details, created_by, pop_name, updated_by) FROM stdin;
2025-03-16 18:25:31.855376+00	2025-03-16 18:25:31.855393+00	t	5fad9405-6ec4-4e82-aef8-5d351c75c380	3071523B00003	Energy Meter	MINOR		\N	61526a69-c86f-4396-a8e4-5a8868b3a75b	b8b9df59-d288-4eb3-be2d-314fe7f3d9f4	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:26:17.865009+00	2025-03-16 18:26:17.865035+00	t	92b6a2ae-5c9d-46c7-97b6-b47ce9f505e4	COLOCITY_THERMOHYGROMETER	Thermohygrometer	MINOR		\N	61526a69-c86f-4396-a8e4-5a8868b3a75b	b8b9df59-d288-4eb3-be2d-314fe7f3d9f4	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:27:08.597037+00	2025-03-16 18:27:08.597058+00	t	b74446b3-e25a-465d-beeb-8c991c589b74	GREEN_POWER_GENERATOR	Generator	MINOR		\N	61526a69-c86f-4396-a8e4-5a8868b3a75b	e0ac95b7-834b-4c3c-97bf-2aeb8cdc4ef2	61526a69-c86f-4396-a8e4-5a8868b3a75b
2025-03-16 18:27:30.893027+00	2025-03-16 18:27:30.893048+00	t	28169ac6-1978-48fb-bc76-52db2b8ea4f6	GREEN_POWER_THERMOHYGROMETER	Thermohygrometer	MINOR		\N	61526a69-c86f-4396-a8e4-5a8868b3a75b	e0ac95b7-834b-4c3c-97bf-2aeb8cdc4ef2	61526a69-c86f-4396-a8e4-5a8868b3a75b
\.


--
-- Data for Name: pops; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.pops (created_at, updated_at, is_active, id, name, code, address, latitude, longitude, status, network_status, created_by, updated_by, user_id) FROM stdin;
2025-03-16 18:23:40.727034+00	2025-03-16 18:23:40.727056+00	t	b8b9df59-d288-4eb3-be2d-314fe7f3d9f4	Colo City	1000	Amtoli, Mohakhali, Dhaka	-9	10	MINOR	ONLINE	61526a69-c86f-4396-a8e4-5a8868b3a75b	61526a69-c86f-4396-a8e4-5a8868b3a75b	6aa50456-a3dd-46b4-86f7-d0be50082c2a
2025-03-16 18:24:34.16496+00	2025-03-16 18:24:34.164982+00	t	e0ac95b7-834b-4c3c-97bf-2aeb8cdc4ef2	Green Power	1001	Purbachol, Dhaka	34	21	MINOR	ONLINE	61526a69-c86f-4396-a8e4-5a8868b3a75b	61526a69-c86f-4396-a8e4-5a8868b3a75b	6aa50456-a3dd-46b4-86f7-d0be50082c2a
\.


--
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.role (role_id, name, key) FROM stdin;
e1f69be8-7cb7-44ec-9978-39f0288e62b5	Administrator	admin
7bf2251d-8134-4469-9476-c3876ee87cd8	User	user
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public."user" (last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, user_id, full_name, email, password, contact_number, role_id) FROM stdin;
2025-03-16 18:11:24.532731+00	t			t	t	2025-03-16 18:10:37.679627+00	5be07222-ca5f-48e2-8f43-c0c73e5c668d		duetboyimran@gmail.com	pbkdf2_sha256$390000$1oBmo052pNDAwCVTmbSWqN$vLTX92PI8QmzDmlP9o66AApiliiWbQEYjf6mRJINhq8=		\N
\N	t			t	t	2025-03-16 18:21:21.692392+00	61526a69-c86f-4396-a8e4-5a8868b3a75b	SOS Development Ltd.	admin@gmail.com	pbkdf2_sha256$390000$y1wnkYkYzL9N9ZKIC8aNK1$3kYdm0OhTQcdaR1gyJAlriKSWoPKVSGpWlsXlRQ4Sdc=	01320402434	e1f69be8-7cb7-44ec-9978-39f0288e62b5
\N	t			f	t	2025-03-16 18:21:56.360903+00	6aa50456-a3dd-46b4-86f7-d0be50082c2a	Colo City	testuser@gmail.com	pbkdf2_sha256$390000$oHRBiuCOWjreAntwL6IuIZ$GuVnaViGmmjc18huYxw4y+hn9/7I454ECwdFfpT7Dss=	01320402434	7bf2251d-8134-4469-9476-c3876ee87cd8
\.


--
-- Data for Name: user_groups; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.user_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: user_user_permissions; Type: TABLE DATA; Schema: public; Owner: dcim_user
--

COPY public.user_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dcim_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dcim_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dcim_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 164, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dcim_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 47, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dcim_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 41, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dcim_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


--
-- Name: user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dcim_user
--

SELECT pg_catalog.setval('public.user_groups_id_seq', 1, false);


--
-- Name: user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dcim_user
--

SELECT pg_catalog.setval('public.user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: pop_device_states pop_device_states_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pop_device_states
    ADD CONSTRAINT pop_device_states_pkey PRIMARY KEY (id);


--
-- Name: pop_devices pop_devices_code_key; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pop_devices
    ADD CONSTRAINT pop_devices_code_key UNIQUE (code);


--
-- Name: pop_devices pop_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pop_devices
    ADD CONSTRAINT pop_devices_pkey PRIMARY KEY (id);


--
-- Name: pops pops_code_key; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pops
    ADD CONSTRAINT pops_code_key UNIQUE (code);


--
-- Name: pops pops_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pops
    ADD CONSTRAINT pops_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (role_id);


--
-- Name: user user_email_key; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- Name: user_groups user_groups_customuser_id_group_id_69b568ae_uniq; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT user_groups_customuser_id_group_id_69b568ae_uniq UNIQUE (customuser_id, group_id);


--
-- Name: user_groups user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT user_groups_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- Name: user_user_permissions user_user_permissions_customuser_id_permission_id_2f47aad7_uniq; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT user_user_permissions_customuser_id_permission_id_2f47aad7_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: user_user_permissions user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: pop_device__created_92ffb3_idx; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_device__created_92ffb3_idx ON public.pop_device_states USING btree (created_at);


--
-- Name: pop_device__is_acti_9882fa_idx; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_device__is_acti_9882fa_idx ON public.pop_device_states USING btree (is_active);


--
-- Name: pop_device_states_created_by_aa6bcf76; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_device_states_created_by_aa6bcf76 ON public.pop_device_states USING btree (created_by);


--
-- Name: pop_device_states_device_code_0f8de54c; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_device_states_device_code_0f8de54c ON public.pop_device_states USING btree (device_code);


--
-- Name: pop_device_states_updated_by_5b898b52; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_device_states_updated_by_5b898b52 ON public.pop_device_states USING btree (updated_by);


--
-- Name: pop_devices_code_26ebca1e_like; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_devices_code_26ebca1e_like ON public.pop_devices USING btree (code varchar_pattern_ops);


--
-- Name: pop_devices_code_7fbb04_idx; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_devices_code_7fbb04_idx ON public.pop_devices USING btree (code);


--
-- Name: pop_devices_created_41f063_idx; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_devices_created_41f063_idx ON public.pop_devices USING btree (created_at);


--
-- Name: pop_devices_created_by_82ba30a8; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_devices_created_by_82ba30a8 ON public.pop_devices USING btree (created_by);


--
-- Name: pop_devices_is_acti_f871b6_idx; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_devices_is_acti_f871b6_idx ON public.pop_devices USING btree (is_active);


--
-- Name: pop_devices_pop_name_1b0a0b94; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_devices_pop_name_1b0a0b94 ON public.pop_devices USING btree (pop_name);


--
-- Name: pop_devices_status_a72247_idx; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_devices_status_a72247_idx ON public.pop_devices USING btree (status);


--
-- Name: pop_devices_updated_by_1263a67c; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pop_devices_updated_by_1263a67c ON public.pop_devices USING btree (updated_by);


--
-- Name: pops_code_d88d546c_like; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pops_code_d88d546c_like ON public.pops USING btree (code varchar_pattern_ops);


--
-- Name: pops_created_by_5d48d6e5; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pops_created_by_5d48d6e5 ON public.pops USING btree (created_by);


--
-- Name: pops_updated_by_ccf0e0c6; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pops_updated_by_ccf0e0c6 ON public.pops USING btree (updated_by);


--
-- Name: pops_user_id_45a1dd60; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX pops_user_id_45a1dd60 ON public.pops USING btree (user_id);


--
-- Name: user_email_54dc62b2_like; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX user_email_54dc62b2_like ON public."user" USING btree (email varchar_pattern_ops);


--
-- Name: user_groups_customuser_id_246bd336; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX user_groups_customuser_id_246bd336 ON public.user_groups USING btree (customuser_id);


--
-- Name: user_groups_group_id_b76f8aba; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX user_groups_group_id_b76f8aba ON public.user_groups USING btree (group_id);


--
-- Name: user_role_id_c3a87a3d; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX user_role_id_c3a87a3d ON public."user" USING btree (role_id);


--
-- Name: user_user_permissions_customuser_id_3b468234; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX user_user_permissions_customuser_id_3b468234 ON public.user_user_permissions USING btree (customuser_id);


--
-- Name: user_user_permissions_permission_id_9deb68a3; Type: INDEX; Schema: public; Owner: dcim_user
--

CREATE INDEX user_user_permissions_permission_id_9deb68a3 ON public.user_user_permissions USING btree (permission_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pop_device_states pop_device_states_created_by_aa6bcf76_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pop_device_states
    ADD CONSTRAINT pop_device_states_created_by_aa6bcf76_fk_user_user_id FOREIGN KEY (created_by) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pop_device_states pop_device_states_device_code_0f8de54c_fk_pop_devices_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pop_device_states
    ADD CONSTRAINT pop_device_states_device_code_0f8de54c_fk_pop_devices_id FOREIGN KEY (device_code) REFERENCES public.pop_devices(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pop_device_states pop_device_states_updated_by_5b898b52_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pop_device_states
    ADD CONSTRAINT pop_device_states_updated_by_5b898b52_fk_user_user_id FOREIGN KEY (updated_by) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pop_devices pop_devices_created_by_82ba30a8_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pop_devices
    ADD CONSTRAINT pop_devices_created_by_82ba30a8_fk_user_user_id FOREIGN KEY (created_by) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pop_devices pop_devices_pop_name_1b0a0b94_fk_pops_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pop_devices
    ADD CONSTRAINT pop_devices_pop_name_1b0a0b94_fk_pops_id FOREIGN KEY (pop_name) REFERENCES public.pops(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pop_devices pop_devices_updated_by_1263a67c_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pop_devices
    ADD CONSTRAINT pop_devices_updated_by_1263a67c_fk_user_user_id FOREIGN KEY (updated_by) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pops pops_created_by_5d48d6e5_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pops
    ADD CONSTRAINT pops_created_by_5d48d6e5_fk_user_user_id FOREIGN KEY (created_by) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pops pops_updated_by_ccf0e0c6_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pops
    ADD CONSTRAINT pops_updated_by_ccf0e0c6_fk_user_user_id FOREIGN KEY (updated_by) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pops pops_user_id_45a1dd60_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.pops
    ADD CONSTRAINT pops_user_id_45a1dd60_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_groups user_groups_customuser_id_246bd336_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT user_groups_customuser_id_246bd336_fk_user_user_id FOREIGN KEY (customuser_id) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_groups user_groups_group_id_b76f8aba_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.user_groups
    ADD CONSTRAINT user_groups_group_id_b76f8aba_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user user_role_id_c3a87a3d_fk_role_role_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_role_id_c3a87a3d_fk_role_role_id FOREIGN KEY (role_id) REFERENCES public.role(role_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_permissions user_user_permission_permission_id_9deb68a3_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT user_user_permission_permission_id_9deb68a3_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_permissions user_user_permissions_customuser_id_3b468234_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: dcim_user
--

ALTER TABLE ONLY public.user_user_permissions
    ADD CONSTRAINT user_user_permissions_customuser_id_3b468234_fk_user_user_id FOREIGN KEY (customuser_id) REFERENCES public."user"(user_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Debian 12.22-1.pgdg120+1)
-- Dumped by pg_dump version 12.22 (Debian 12.22-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database cluster dump complete
--

