networks:
  dcim_network:
    driver: bridge

services:
  redis:
    image: "redis:alpine"
    restart: "on-failure"
    expose:
      - 6379
    networks:
      - dcim_network

  dcim_backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 4000
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    links:
      - "redis"
    volumes:
      - dcim_staticfiles:/opt/app/static/static_root
      - dcim_mediafiles:/opt/app/media/
      - .:/opt/app
    restart: on-failure
    networks:
      - dcim_network

  dcim_backend_celery:
    build: .
    command: celery  -A dcim worker -l info
    restart: "on-failure"
    depends_on:
      - "redis"
      - "dcim_backend"
    volumes:
      - .:/opt/app
    networks:
      - dcim_network

  dcim_backend_celery-beat:
    build: .
    command: celery -A dcim beat -l info
    restart: "on-failure"
    depends_on:
      - "redis"
      - "dcim_backend"
    volumes:
      - .:/opt/app
    networks:
      - dcim_network

  postgres:
    container_name: dcim_postgres
    image: postgres:12
    restart: "on-failure"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=dcim
      - POSTGRES_USER=dcim_user
      - POSTGRES_PASSWORD=dcim_password
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - dcim_postgres_data:/var/lib/postgresql/data
    networks:
      - dcim_network

  mongo:
    image: mongo
    container_name: dcim_mongo
    restart: "on-failure"
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_DB_PASSWORD}
    command: mongod --bind_ip 0.0.0.0 --auth
    volumes:
      - dcim_mongodb_data:/data/db
    networks:
      - dcim_network

  broker_dcim:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd base/broker && python consumer.py"
    restart: on-failure
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/opt/app
    networks:
      - dcim_network

  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - dcim_staticfiles:/opt/staticfiles
      - dcim_mediafiles:/opt/mediafiles
    depends_on:
      - "dcim_backend"
    networks:
      - dcim_network

volumes:
  dcim_staticfiles:
  dcim_mediafiles:
  dcim_mongodb_data:
  dcim_postgres_data:
