from djongo import models as mongo_models

# Model for Real Time Data of Compere Power Meter
class RTModelCPM(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_date = mongo_models.DateField(auto_now_add=True)
    created_time = mongo_models.TimeField(auto_now_add=True)
    device_code = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    uab = mongo_models.FloatField()
    ubc = mongo_models.FloatField()
    uca = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    zyggl = mongo_models.FloatField()
    qa = mongo_models.FloatField()
    qb = mongo_models.FloatField()
    qc = mongo_models.FloatField()
    zwggl = mongo_models.FloatField()
    sa = mongo_models.FloatField()
    sb = mongo_models.FloatField()
    sc = mongo_models.FloatField()
    zszgl = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    zglys = mongo_models.FloatField()
    f = mongo_models.FloatField()
    u0 = mongo_models.FloatField()
    u_plus = mongo_models.FloatField()
    u_minus = mongo_models.FloatField()
    i0 = mongo_models.FloatField()
    i_plus = mongo_models.FloatField()
    i_minus = mongo_models.FloatField()
    uxja = mongo_models.FloatField()
    uxjb = mongo_models.FloatField()
    uxjc = mongo_models.FloatField()
    ixja = mongo_models.FloatField()
    ixjb = mongo_models.FloatField()
    ixjc = mongo_models.FloatField()
    unb = mongo_models.FloatField()
    inb = mongo_models.FloatField()
    pdm = mongo_models.FloatField()
    qdm = mongo_models.FloatField()
    sdm = mongo_models.FloatField()
    
    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.device_code
    

# Model for Temporary Real Time Data of Compere Power Meter
class TemporaryRTModelCPM(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_date = mongo_models.DateField(auto_now_add=True)
    created_time = mongo_models.TimeField(auto_now_add=True)
    device_code = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    # uab = mongo_models.FloatField()
    # ubc = mongo_models.FloatField()
    # uca = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    zyggl = mongo_models.FloatField()
    # qa = mongo_models.FloatField()
    # qb = mongo_models.FloatField()
    # qc = mongo_models.FloatField()
    # zwggl = mongo_models.FloatField()
    # sa = mongo_models.FloatField()
    # sb = mongo_models.FloatField()
    # sc = mongo_models.FloatField()
    # zszgl = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    zglys = mongo_models.FloatField()
    f = mongo_models.FloatField()
    # u0 = mongo_models.FloatField()
    # u_plus = mongo_models.FloatField()
    # u_minus = mongo_models.FloatField()
    # i0 = mongo_models.FloatField()
    # i_plus = mongo_models.FloatField()
    # i_minus = mongo_models.FloatField()
    # uxja = mongo_models.FloatField()
    # uxjb = mongo_models.FloatField()
    # uxjc = mongo_models.FloatField()
    # ixja = mongo_models.FloatField()
    # ixjb = mongo_models.FloatField()
    # ixjc = mongo_models.FloatField()
    # unb = mongo_models.FloatField()
    # inb = mongo_models.FloatField()
    pdm = mongo_models.FloatField()
    qdm = mongo_models.FloatField()
    sdm = mongo_models.FloatField()
    
    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.device_code
    

# Mongo Model for Today Real Time Data of Compere Power Meter
class TodayRTModelCPM(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_date = mongo_models.DateField(auto_now_add=True)
    created_time = mongo_models.TimeField(auto_now_add=True)
    device_code = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    # uab = mongo_models.FloatField()
    # ubc = mongo_models.FloatField()
    # uca = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    zyggl = mongo_models.FloatField()
    # qa = mongo_models.FloatField()
    # qb = mongo_models.FloatField()
    # qc = mongo_models.FloatField()
    # zwggl = mongo_models.FloatField()
    # sa = mongo_models.FloatField()
    # sb = mongo_models.FloatField()
    # sc = mongo_models.FloatField()
    # zszgl = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    zglys = mongo_models.FloatField()
    f = mongo_models.FloatField()
    # u0 = mongo_models.FloatField()
    # u_plus = mongo_models.FloatField()
    # u_minus = mongo_models.FloatField()
    # i0 = mongo_models.FloatField()
    # i_plus = mongo_models.FloatField()
    # i_minus = mongo_models.FloatField()
    # uxja = mongo_models.FloatField()
    # uxjb = mongo_models.FloatField()
    # uxjc = mongo_models.FloatField()
    # ixja = mongo_models.FloatField()
    # ixjb = mongo_models.FloatField()
    # ixjc = mongo_models.FloatField()
    # unb = mongo_models.FloatField()
    # inb = mongo_models.FloatField()
    pdm = mongo_models.FloatField()
    qdm = mongo_models.FloatField()
    sdm = mongo_models.FloatField()
    
    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.device_code


# Mongo Model for last 7 days Real Time Data of Compere Power Meter
class Last7DaysRTModelCPM(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_date = mongo_models.DateField(auto_now_add=True)
    created_time = mongo_models.TimeField(auto_now_add=True)
    device_code = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    # uab = mongo_models.FloatField()
    # ubc = mongo_models.FloatField()
    # uca = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    zyggl = mongo_models.FloatField()
    # qa = mongo_models.FloatField()
    # qb = mongo_models.FloatField()
    # qc = mongo_models.FloatField()
    # zwggl = mongo_models.FloatField()
    # sa = mongo_models.FloatField()
    # sb = mongo_models.FloatField()
    # sc = mongo_models.FloatField()
    # zszgl = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    zglys = mongo_models.FloatField()
    f = mongo_models.FloatField()
    # u0 = mongo_models.FloatField()
    # u_plus = mongo_models.FloatField()
    # u_minus = mongo_models.FloatField()
    # i0 = mongo_models.FloatField()
    # i_plus = mongo_models.FloatField()
    # i_minus = mongo_models.FloatField()
    # uxja = mongo_models.FloatField()
    # uxjb = mongo_models.FloatField()
    # uxjc = mongo_models.FloatField()
    # ixja = mongo_models.FloatField()
    # ixjb = mongo_models.FloatField()
    # ixjc = mongo_models.FloatField()
    # unb = mongo_models.FloatField()
    # inb = mongo_models.FloatField()
    pdm = mongo_models.FloatField()
    qdm = mongo_models.FloatField()
    sdm = mongo_models.FloatField()
    
    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.device_code
    

# Mongo Model for last 30 days Real Time Data of Compere Power Meter
class Last30DaysRTModelCPM(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_date = mongo_models.DateField(auto_now_add=True)
    created_time = mongo_models.TimeField(auto_now_add=True)
    device_code = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    # uab = mongo_models.FloatField()
    # ubc = mongo_models.FloatField()
    # uca = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    zyggl = mongo_models.FloatField()
    # qa = mongo_models.FloatField()
    # qb = mongo_models.FloatField()
    # qc = mongo_models.FloatField()
    # zwggl = mongo_models.FloatField()
    # sa = mongo_models.FloatField()
    # sb = mongo_models.FloatField()
    # sc = mongo_models.FloatField()
    # zszgl = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    zglys = mongo_models.FloatField()
    f = mongo_models.FloatField()
    # u0 = mongo_models.FloatField()
    # u_plus = mongo_models.FloatField()
    # u_minus = mongo_models.FloatField()
    # i0 = mongo_models.FloatField()
    # i_plus = mongo_models.FloatField()
    # i_minus = mongo_models.FloatField()
    # uxja = mongo_models.FloatField()
    # uxjb = mongo_models.FloatField()
    # uxjc = mongo_models.FloatField()
    # ixja = mongo_models.FloatField()
    # ixjb = mongo_models.FloatField()
    # ixjc = mongo_models.FloatField()
    # unb = mongo_models.FloatField()
    # inb = mongo_models.FloatField()
    pdm = mongo_models.FloatField()
    qdm = mongo_models.FloatField()
    sdm = mongo_models.FloatField()
    
    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.device_code
    

# Mongo Model for This Year Real Time Data of Compere Power Meter
class ThisYearRTModelCPM(mongo_models.Model):
    _id = mongo_models.ObjectIdField()
    created_date = mongo_models.DateField(auto_now_add=True)
    created_time = mongo_models.TimeField(auto_now_add=True)
    device_code = mongo_models.CharField(max_length=360)
    topic = mongo_models.CharField(max_length=256)
    ua = mongo_models.FloatField()
    ub = mongo_models.FloatField()
    uc = mongo_models.FloatField()
    ia = mongo_models.FloatField()
    ib = mongo_models.FloatField()
    ic = mongo_models.FloatField()
    # uab = mongo_models.FloatField()
    # ubc = mongo_models.FloatField()
    # uca = mongo_models.FloatField()
    pa = mongo_models.FloatField()
    pb = mongo_models.FloatField()
    pc = mongo_models.FloatField()
    zyggl = mongo_models.FloatField()
    # qa = mongo_models.FloatField()
    # qb = mongo_models.FloatField()
    # qc = mongo_models.FloatField()
    # zwggl = mongo_models.FloatField()
    # sa = mongo_models.FloatField()
    # sb = mongo_models.FloatField()
    # sc = mongo_models.FloatField()
    # zszgl = mongo_models.FloatField()
    pfa = mongo_models.FloatField()
    pfb = mongo_models.FloatField()
    pfc = mongo_models.FloatField()
    zglys = mongo_models.FloatField()
    f = mongo_models.FloatField()
    # u0 = mongo_models.FloatField()
    # u_plus = mongo_models.FloatField()
    # u_minus = mongo_models.FloatField()
    # i0 = mongo_models.FloatField()
    # i_plus = mongo_models.FloatField()
    # i_minus = mongo_models.FloatField()
    # uxja = mongo_models.FloatField()
    # uxjb = mongo_models.FloatField()
    # uxjc = mongo_models.FloatField()
    # ixja = mongo_models.FloatField()
    # ixjb = mongo_models.FloatField()
    # ixjc = mongo_models.FloatField()
    # unb = mongo_models.FloatField()
    # inb = mongo_models.FloatField()
    pdm = mongo_models.FloatField()
    qdm = mongo_models.FloatField()
    sdm = mongo_models.FloatField()
    
    class Meta:
        _use_db = 'nonrel'

    def __str__(self):
        return self.device_code